CREATE TABLE currencies (
cur_id NVARCHAR(5),
country NVARCHAR(50)
);

INSERT INTO currencies VALUES('AED', 'United Arab Emirates');
INSERT INTO currencies VALUES('AFN', 'Afghanistan');
INSERT INTO currencies VALUES('ALL', 'Albania');
INSERT INTO currencies VALUES('AMD', 'Armenia');
INSERT INTO currencies VALUES('ANG', 'Netherlands');
INSERT INTO currencies VALUES('AOA', 'Angola');
INSERT INTO currencies VALUES('ARS', 'Argentina');
INSERT INTO currencies VALUES('AUD', 'Australia');
INSERT INTO currencies VALUES('AWG', 'Aruba');
INSERT INTO currencies VALUES('AZN', 'Azerbaijan');
INSERT INTO currencies VALUES('BAM', 'Bosnia and Herzegovina');
INSERT INTO currencies VALUES('BBD', 'Barbados');
INSERT INTO currencies VALUES('BDT', 'Bangladesh');
INSERT INTO currencies VALUES('BGN', 'Bulgaria');
INSERT INTO currencies VALUES('BHD', 'Bahrain');
INSERT INTO currencies VALUES('BIF', 'Burundi');
INSERT INTO currencies VALUES('BMD', 'Bermuda');
INSERT INTO currencies VALUES('BND', 'Brunei');
INSERT INTO currencies VALUES('BRL', 'Brazil');
INSERT INTO currencies VALUES('BOB', 'Bolivia');
INSERT INTO currencies VALUES('BSD', 'Bahamas');
INSERT INTO currencies VALUES('BTN', 'Bhutan');
INSERT INTO currencies VALUES('BWP', 'Botswana');
INSERT INTO currencies VALUES('BYN', 'Belarus');
INSERT INTO currencies VALUES('BZD', 'Belize');
INSERT INTO currencies VALUES('CAD', 'Canada');
INSERT INTO currencies VALUES('CDF', 'Congo');
INSERT INTO currencies VALUES('CHF', 'Switzerland');
INSERT INTO currencies VALUES('CLF', 'Chile');
INSERT INTO currencies VALUES('CLP', 'Chile');
INSERT INTO currencies VALUES('CNH', 'China (mainland)');
INSERT INTO currencies VALUES('CNY', 'China');
INSERT INTO currencies VALUES('COP', 'Colombia');
INSERT INTO currencies VALUES('CRC', 'Costa Rica');
INSERT INTO currencies VALUES('CUC', 'Cuba');
INSERT INTO currencies VALUES('CUP', 'Cuba');
INSERT INTO currencies VALUES('CVE', 'Cape Verde');
INSERT INTO currencies VALUES('CZK', 'Czech Republic');
INSERT INTO currencies VALUES('DJF', 'Djibouti');
INSERT INTO currencies VALUES('DKK', 'Denmark');
INSERT INTO currencies VALUES('DOP', 'Dominican Republic');
INSERT INTO currencies VALUES('DZD', 'Algeria');
INSERT INTO currencies VALUES('EGP', 'Egypt');
INSERT INTO currencies VALUES('ERN', 'Eritrea');
INSERT INTO currencies VALUES('ETB', 'Ethiopia');
INSERT INTO currencies VALUES('FJD', 'Fiji');
INSERT INTO currencies VALUES('FKP', 'Falkland Islands');
INSERT INTO currencies VALUES('GBP', 'United Kingdom');
INSERT INTO currencies VALUES('GEL', 'Georgia');
INSERT INTO currencies VALUES('GGP', 'Guernsey');
INSERT INTO currencies VALUES('GHS', 'Ghana');
INSERT INTO currencies VALUES('GIP', 'Gibraltar');
INSERT INTO currencies VALUES('GMD', 'Gambia');
INSERT INTO currencies VALUES('GNF', 'Guinea');
INSERT INTO currencies VALUES('GTQ', 'Guatemala');
INSERT INTO currencies VALUES('GYD', 'Guyana');
INSERT INTO currencies VALUES('HKD', 'Hong Kong');
INSERT INTO currencies VALUES('HNL', 'Honduras');
INSERT INTO currencies VALUES('HRK', 'Croatia');
INSERT INTO currencies VALUES('HTG', 'Haiti');
INSERT INTO currencies VALUES('HUF', 'Hungary');
INSERT INTO currencies VALUES('IDR', 'Indonesia');
INSERT INTO currencies VALUES('ILS', 'Israel');
INSERT INTO currencies VALUES('INR', 'India');
INSERT INTO currencies VALUES('IQD', 'Iraq');
INSERT INTO currencies VALUES('IRR', 'Iran');
INSERT INTO currencies VALUES('ISK', 'Iceland');
INSERT INTO currencies VALUES('JEP', 'Jersey');
INSERT INTO currencies VALUES('JMD', 'Jamaica');
INSERT INTO currencies VALUES('JOD', 'Jordan');
INSERT INTO currencies VALUES('JPY', 'Japan');
INSERT INTO currencies VALUES('KES', 'Kenya');
INSERT INTO currencies VALUES('KGS', 'Kyrgyzstan');
INSERT INTO currencies VALUES('KHR', 'Cambodia');
INSERT INTO currencies VALUES('KMF', 'Comoros');
INSERT INTO currencies VALUES('KRW', 'South Korea');
INSERT INTO currencies VALUES('KRW', 'South Korea');
INSERT INTO currencies VALUES('KWD', 'Kuwait');
INSERT INTO currencies VALUES('KYD', 'Cayman Islands');
INSERT INTO currencies VALUES('KZT', 'Kazakhstan');
INSERT INTO currencies VALUES('LAK', 'Laos');
INSERT INTO currencies VALUES('LBP', 'Lebanon');
INSERT INTO currencies VALUES('LKR', 'Sri Lanka');
INSERT INTO currencies VALUES('LRD', 'Liberia');
INSERT INTO currencies VALUES('LSL', 'Lesotho');
INSERT INTO currencies VALUES('LYD', 'Libya');
INSERT INTO currencies VALUES('MAD', 'Morocco');
INSERT INTO currencies VALUES('MDL', 'Moldova');
INSERT INTO currencies VALUES('MGA', 'Madagascar');
INSERT INTO currencies VALUES('MKD', 'North Makedonia');
INSERT INTO currencies VALUES('MMK', 'Myanmar');
INSERT INTO currencies VALUES('MNT', 'Mongolia');
INSERT INTO currencies VALUES('MOP', 'Macau');
INSERT INTO currencies VALUES('MRO', 'Mauritania');
INSERT INTO currencies VALUES('MRU', 'Mauritania');
INSERT INTO currencies VALUES('MUR', 'Mauritius');
INSERT INTO currencies VALUES('MVR', 'Maldives');
INSERT INTO currencies VALUES('MWK', 'Malawi');
INSERT INTO currencies VALUES('MXN', 'Mexico');
INSERT INTO currencies VALUES('MYR', 'Malaysia');
INSERT INTO currencies VALUES('MZN', 'Mozambique');
INSERT INTO currencies VALUES('NAD', 'Namibia');
INSERT INTO currencies VALUES('NGN', 'Nigeria');
INSERT INTO currencies VALUES('NIO', 'Nicaragua');
INSERT INTO currencies VALUES('NOK', 'Norway');
INSERT INTO currencies VALUES('NPR', 'Nepal');
INSERT INTO currencies VALUES('NZD', 'New Zealand');
INSERT INTO currencies VALUES('OMR', 'Oman');
INSERT INTO currencies VALUES('PAB', 'Panama');
INSERT INTO currencies VALUES('PEN', 'Peru');
INSERT INTO currencies VALUES('PGK', 'Papua New Guinea');
INSERT INTO currencies VALUES('PHP', 'Philippines');
INSERT INTO currencies VALUES('PKR', 'Pakistan');
INSERT INTO currencies VALUES('PLN', 'Poland');
INSERT INTO currencies VALUES('PYG', 'Paraguay');
INSERT INTO currencies VALUES('QAR', 'Qatar');
INSERT INTO currencies VALUES('RON', 'Romania');
INSERT INTO currencies VALUES('RSD', 'Serbia');
INSERT INTO currencies VALUES('RUB', 'Russia');
INSERT INTO currencies VALUES('RWF', 'Rwanda');
INSERT INTO currencies VALUES('SAR', 'Saudi Arabia');
INSERT INTO currencies VALUES('SBD', 'Solomon Islands');
INSERT INTO currencies VALUES('SCR', 'Seychelles');
INSERT INTO currencies VALUES('SDG', 'Sudan');
INSERT INTO currencies VALUES('SEK', 'Sweden');
INSERT INTO currencies VALUES('SGD', 'Singapore');
INSERT INTO currencies VALUES('SHP', 'Saint Helena');
INSERT INTO currencies VALUES('SLL', 'Sierra Leone');
INSERT INTO currencies VALUES('SOS', 'Somaliland');
INSERT INTO currencies VALUES('SRD', 'Suriname');
INSERT INTO currencies VALUES('SSP', 'South Sudan');
INSERT INTO currencies VALUES('STD', 'São Tomé and Príncipe');
INSERT INTO currencies VALUES('STN', 'São Tomé and Príncipe');
INSERT INTO currencies VALUES('SYP', 'Syria');
INSERT INTO currencies VALUES('SZL', 'Swaziland');
INSERT INTO currencies VALUES('THB', 'Thailand');
INSERT INTO currencies VALUES('TJS', 'Tajikistan');
INSERT INTO currencies VALUES('TMT', 'Turkmenistan');
INSERT INTO currencies VALUES('TND', 'Tunisia');
INSERT INTO currencies VALUES('TRY', 'Turkey');
INSERT INTO currencies VALUES('TTD', 'Trinidad and Tobago');
INSERT INTO currencies VALUES('TWD', 'Taiwan');
INSERT INTO currencies VALUES('TZS', 'Tanzania');
INSERT INTO currencies VALUES('UAH', 'Ukraine');
INSERT INTO currencies VALUES('UGX', 'Uganda');
INSERT INTO currencies VALUES('USD', 'United States');
INSERT INTO currencies VALUES('UYU', 'Uruguay');
INSERT INTO currencies VALUES('UZS', 'Uzbekistan');
INSERT INTO currencies VALUES('VEF', 'Venezuela');
INSERT INTO currencies VALUES('VES', 'Venezuela');
INSERT INTO currencies VALUES('VND', 'Vietnam');
INSERT INTO currencies VALUES('VUV', 'Vanuatu');
INSERT INTO currencies VALUES('WST', 'Samoa');
INSERT INTO currencies VALUES('YER', 'Yemen');
INSERT INTO currencies VALUES('ZAR', 'South Africa');
INSERT INTO currencies VALUES('ZMW', 'Zambia');
INSERT INTO currencies VALUES('ZWL', 'Zimbabwe');

INSERT INTO currencies
SELECT DISTINCT country_id, NULL FROM forbes
LEFT JOIN currencies ON currencies.cur_id = forbes.country_id
WHERE cur_id IS NULL;
 
INSERT INTO currencies
SELECT DISTINCT NULL, country_name FROM covid
LEFT JOIN currencies ON currencies.country = covid.country_name
WHERE country IS NULL;

